#Django 基本資料
django_ip="0.0.0.0"
django_port=8000



# smtp info
mail_port = 465
smtp_server = "smtp.gmail.com"
smtp_login = "mailsender.weiyen@gmail.com" # paste your login generated by Mailtrap
smtp_password = "WeiYen1221" # paste your password generated by Mailtrap

from_sender = "gpumoniter@leadtek.com.tw"
tw_quadro_notifiation_subject = "Taiwan Quadro Price Warning"
tw_quadro_notifiation_list = "weiyen_lin@leadtek.com.tw;kevin_lo@leadtek.com.tw;ashlee@leadtek.com.tw;kevin_tsai@leadtek.com.tw;alicia_tai@leadtek.com.tw;dragon_chuang@leadtek.com.tw;anita_chang@leadtek.com.tw"
# tw_quadro_notifiation_list = "weiyen_lin@leadtek.com.tw"

quadro_error_report_subject = "Quadro Price Crawler Error"
quadro_error_report_list = "weiyen_lin@leadtek.com.tw"


tw_tire_notifiation_subject = "Taiwan Tire Price Warning"
tw_tire_notifiation_list = "weiyen_lin@leadtek.com.tw;jc@cogitomarketing.com"
# tw_tire_notifiation_list = "weiyen_lin@leadtek.com.tw"

tire_error_report_subject = "Tire Price Crawler Error"
tire_error_report_list = "weiyen_lin@leadtek.com.tw"


tw_competitor_geforce_notifiation_subject = "Taiwan Competitor Geforce Price Monitor"
tw_competitor_geforce_notifiation_list = "weiyen_lin@leadtek.com.tw;sabrinna@leadtek.com;denischen@leadtek.com.tw"
# tw_competitor_geforce_notifiation_list = "weiyen_lin@leadtek.com.tw"

competitor_geforce_error_report_subject = "Taiwan Competitor Geforce Crawler Error"
competitor_geforce_error_report_list = "weiyen_lin@leadtek.com.tw"